spring:
    application:
      name: santander-dev-week-2024
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: "sa"
    h2:
      console:
        enabled: true

generative-ai:
  provider: OPENAI


openai:
  base-url: https://api.openai.com
  api-key: ${OPENAI_API_KEY}

gemini:
  base-url: https://generativelanguage.googlepis.com
  api-key: ${GEMINI_API_KEY}